[package]
name = "axprocess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

fs = ["axfs"]

monolithic = ["fs", "axfs/monolithic", "axhal/monolithic", "axtask/monolithic"]

default = ["monolithic"]

[dependencies]
cfg-if = "1.0"
spinlock = { path = "../../crates/spinlock" }
axtask = { path = "../axtask" }
axsync = { path = "../axsync" }
axmem = { path = "../axmem" }
axalloc = { path = "../axalloc" }
axio = { path = "../../crates/axio", features = ["alloc"] }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axerrno = { path = "../../crates/axerrno" }
axconfig = { path = "../axconfig" }
axfs = { path = "../axfs", optional = true }
axsignal = { path = "../axsignal" }
riscv = "0.10"
bitflags = "2.0"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
xmas-elf = "0.9.0"
elf_parser = { path = "../../crates/elf_parser" }