# Architecture identifier.
arch = "riscv64"
# Platform identifier.
platform = "riscv64-qemu-virt"
# Platform family.
family = "riscv64-qemu-virt"

# Base address of the whole physical memory.
phys-memory-base = "0x8000_0000"
# Size of the whole physical memory.
phys-memory-size = "0x800_0000"     # 128M
# Base physical address of the kernel image.
kernel-base-paddr = "0x8020_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_8020_0000"

# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x0c00_0000", "0x21_0000"],   # PLIC
    ["0x1000_0000", "0x1000"],      # UART
    ["0x1000_1000", "0x8000"],      # VirtIO
    ["0x3000_0000", "0x1000_0000"],  # PCI config space
    ["0x4000_0000", "0x4000_0000"],  # PCI memory ranges (ranges 1: 32-bit MMIO space)
]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [
    ["0x1000_1000", "0x1000"],
    ["0x1000_2000", "0x1000"],
    ["0x1000_3000", "0x1000"],
    ["0x1000_4000", "0x1000"],
    ["0x1000_5000", "0x1000"],
    ["0x1000_6000", "0x1000"],
    ["0x1000_7000", "0x1000"],
    ["0x1000_8000", "0x1000"],
]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = "0x3000_0000"
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = "0xff"
# PCI device memory ranges (`ranges` property in device tree).
pci-ranges = [
    ["0x0300_0000", "0x1_0000"],          # PIO space
    ["0x4000_0000", "0x4000_0000"],       # 32-bit MMIO space
    ["0x4_0000_0000", "0x4_0000_0000"],   # 64-but MMIO space
]

# Timer interrupt frequency in Hz.
timer-frequency = "1_000_000"      # 10MHz

# Testcase memory start address.
testcase-memory-start = "0x9000_0000"
# Testcase memory size.
testcase-memory-size = "0x800_0000"
# The base address of the user heap.
user-heap-base = "0x3FA0_0000"
# The base address of the user stack. And the stack bottom is `user-stack-top + max-user-stack-size`.
user-stack-top = "0x3FE0_0000"
# The size of the user heap.
max-user-heap-size = "0x40_0000"
# The size of the user stack.
max-user-stack-size = "0x20_0000"
# The base address of the signal trampoline.
signal-trampoline = "0x4000_0000"