site_name: Starry
site_description: Starry设计文档
nav:
  - Starry: index.md
  - 概述: 概述.md
  - 架构设计: 
    - ArceOS介绍: 架构设计/ArceOS介绍.md
    - Starry结构说明: 架构设计/Starry结构说明.md
  - 设计思路: 设计思路.md
  - 模块介绍:
    - 内核底层模块-axhal: 模块介绍/内核底层模块-axhal.md
    - 内存管理模块-axmem: 模块介绍/内存管理模块-axmem.md
    - 网络模块-axnet: 模块介绍/网络模块-axnet.md
    - 信号模块-axsignal: 模块介绍/信号模块-axsignal.md
    - 任务调度模块-axtask: 模块介绍/任务调度模块-axtask.md
    - 文件系统模块-axfs: 模块介绍/文件系统模块-axfs.md
    - 进程控制模块-axprocess: 模块介绍/进程控制模块-axprocess.md
    - 内核运行时模块-axruntime: 模块介绍/内核运行时模块-axruntime.md
    - 宏内核用户库-starry: 模块介绍/宏内核用户库-starry.md
  - 实现重点:
    - 依赖问题: 实现重点/依赖问题.md
    - 兼容问题: 实现重点/兼容问题.md
    - 宏内核化探讨: 实现重点/宏内核化探讨.md
  - 问题与解决: 问题与解决.md

# 主题
# theme:
#   name: 'material'
#   language: 'zh'  # 配置语言
#   palette: # 颜色
#     primary: 'purple'
#     accent: 'indigo'
#   feature:
#     tabs: true  # 横向导航

# [UI]
theme:
  name: material
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: blue # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  # - pymdownx.betterem:  # 对加粗和斜体更好的检测
  #     smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

# PDF导出插件
plugins:
  - search
  # - pdf-export #这个插件还有点问题，没有更新
#扩展样式
extra_css:
  - resources/css/extra.css